language: scala
scala:
- 2.11.4
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
  - /^[0-9].[0-9].[0-9]$/
cache:
  directories:
  - $HOME/.m2

before_script:
- test "$TRAVIS_PULL_REQUEST" == "false" && git clone -b travis `git config --get remote.origin.url` target/travis || true

install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Not a PR Build" && [ "IS_${TRAVIS_TAG}" != "IS_" ] && echo "Is tag build $TRAVIS_TAG" || echo "."'
- '[ "IS_${TRAVIS_TAG}" != "IS_" ] && mvn versions:set -DnewVersion=$TRAVIS_TAG -P core || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "Deploying..." && mvn deploy site-deploy -P core -DskipTests=true --settings target/travis/settings.xml -Dgithub.global.oauth2Token=$GITHUB_TOKEN || echo "Testing..." && mvn -q -P core test -B'

after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt ++2.11.4 coverageAggregate || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt ++2.11.4 coveralls || true'

env:
  global:
  - MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"
  - secure: z+5AQ0JizGu1C84dU+ZRaeOSOPT30K9Q8VAby+UnSoLp6WBc2pmHuR7NIXvKq+umetLTZ1H0IpxseXAdwxTfhhXK3133t0xWaDx/9JqbbmOx7w2AoywL4+QzxO5d/QuGWuNwXrOMUQh0bf3UkQEBB/1WSEsbt87Z/cC9QylF4bu3qN6BOXh86pMkScRM+imvWwYX3E2GRKXnrsOhDjCozYIEoHDGxyuzF0uszc82RyW4aC3BcKQU0KBr6veHxMFCsEv0i/N1An31Lkw40J6FLlEQK6RTWFtXlLhNv7PfkuqOfFm3N69qCdsjwATaEDO+b3USs/Qe9bjL87NJ+87UeJJXmigbI0+13Au/Dv9AYwr3mnV3FMOC2Hx4+q7MBWEaBTWJK6wsboz0i6csfJMVdcJs1Pzo5RVyN3b92NlwMzGhtdW3vHYxGuwt5W13gSkwpGIcSfWe/Aqiju5AXUh1IZEaYQR0O2VPF4cSL+BrRFxl1Ovo893ReXAEYczwIFrdVCx5Y3RlemW5cTCFzi/5RRz1AmlBxhOB06y0Gu1QZmGD4sip7V9GqEg/fkuZfmtjOX1tcRWQZGTQp4OQn5QurqH5j2uZ+Q0S2kGyJbg4JQ73hDjn3RLS0zMbrS9iRGE86D8jOxvuN9U25htu69jFelLM/xD0oxvCjPMroXz2d6g=
  - secure: ieeWY45bUzeOv4zJcAdEopj7CEkTPxkKgQyPYSFUN3KQXSqT7GqMA3UxIbTw6K//BoMKegXfJionDruhaZWxJ8R6xrzq0oSVvODoTN7gkYBHqjseWBOH6Z11j66cx1ZxuPYcYkTy2TCZ7lhYfGolchhG8mSEhev09OH1BQ8xUgCFjYtXcCCOp+ESs78tTsvwJJJuJfiWqQTloeg+he8DG36nC7KO98J38RvzkjFGvLfntDV6A9sxCOLAFuYXFSlWOwy9finZbSejBaSW1iu1KcW2xrlHSaRLun30cRs7sliUmnqWk7+eNwgyAifHd2hmMMLuNVeh3hJm11/vsQqdmZMsdNdg+XMJ+aA21Hxs8oFA813T8LrjkbKUmBdGK6ARMPwSEh1Hl4/JUDLrlaY9KED4mu7CpjdKxtQL3E1z2qqQkSX8odSwB3HrViktlQtJTLkNmrNwl0UTHzTIx5qEsIgkHRSjLMSjsxoMGGbS8QEPKP2NjpY+yOq/oOKVwseyhp74I++ueQV9VGQ2CJ5o4KNV5opkStCImyd2gLgGXu08YkAQuArFvY+qMgZAodjZMJz2obMyI2qkNnq8PXd5Gxxirb5IReGHszc3tnRaSKySqRlmZ/ayt+Vleyx88urATH0La+Rfams+Tc6xitIVGQboKF8O1bmoiQhZOWjo+Ww=
  - secure: E9mGFAqB2fy8yJJov/Axbt8WqZP26WYtzQJBXTJRjN3Zgnoi8k0x7Xq1X/I/mp/cX3qIgKctVlZs54rGKCgSc4KVJqYHSVUXzHn40VN/fBN3Oeey9sYXakUHlM+kWNNS8P0q9V/4TQuANOU+M7cqeCf+cy1Lyrk4Msf741sxx+2tdXGeirj6DEQ05C4CZp2YnQ67nuf6ngXhFq5PTrbc3w3irEJ0kM0u5qkwzaHvtm3tkp6RuKkEEvW29Fq8x4UcmlsUeLmXYOiltD0SnGu/wO1ddqzVn8L/fRjgbpb1AEYaaKOhZKaZRHzwMO0uaOzpo63EFXmXTIXXyVeYA00MIcQvANq3LiKumA5NJAWDnWHv3H4YtV7rE+PoUoUKvuD0YA7uR/teSDzeKePw6ps+8mek6sX92OG2xj4SKWptnkr5XRzbrIgBD+7NZCiC9wvqLg0qYg8h8F4TYmAMedxfJpEEs0GuLynIRJqY3ZugqlpoixTXIU4tLH4xpYCKiW8U6OOrjUug20xmSbWwSiUjwS0HW7+VKFhsVd0W6jr0DoOz3x50VfIp6z1uiFIJfPS3QSkpdVB0xpCBfSk1np7ZjLVIicfZMThv4LmJ8oQmB4eMXYd0CzdNPMPN/nuarVWF1LGnvWJaGBFF8Ce/QMV3iSeKqyJu1bK8Vb0W8FKtRRc=
